### ISSUE TITLE
ExtractedFeatures

### ISSUE THREAD

**Issue by GoodWing** [Abhishek-Iyer1/emotion-classifcation-eeg-seed-ensemble#3]
Hello, I am also studying the seed data set, and I have applied for the seed data set, but your processing file should be on google drive, can you share it with me?

**Comment by Abhishek-Iyer1** [comment]
Hey, all the code can needed to process the dataset can be found in the repo and can be tailored for your use. If you are asking if I can share with you the Processed features of the SEED dataset, that unfortunately I cannot. It is not open to redistribution and can only be gained through the appropriate channels. Let me know if I misunderstood the issue or if there is something else or else I will close the issue within 48 hours.

**Comment by GoodWing** [comment]
> Hey, all the code can needed to process the dataset can be found in the repo and can be tailored for your use. If you are asking if I can share with you the Processed features of the SEED dataset, that unfortunately I cannot. It is not open to redistribution and can only be gained through the appropriate channels. Let me know if I misunderstood the issue or if there is something else or else I will close the issue within 48 hours.

Hello, what I said is not clear, there are "DE_data_all_corrected.mat" and "label.mat" in your code. I don’t know how to deal with these two data files

**Comment by Abhishek-Iyer1** [comment]
Those are the names of the files generated after you run the preprocessed_eeg code from the SEED website using the matlab code provided in the repo. They contain all the data in a 4D array consolidated instead of separate examples. So you can upload to your drive or use locally once you run the matlab code on the preprocessed features. Labels.mat doesn't need to be changed I believe. I hope now it is clear
