### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by maneaionut** [Abhishek-Iyer1/emotion-classifcation-eeg-seed-ensemble#7]
Hi! Can you help me please with the code for generating the labels.mat file?

**Comment by Abhishek-Iyer1** [comment]
Hey, please let me know what exact issue you are facing and what is the bug in the code?

**Comment by maneaionut** [comment]
I cannot find how to construct the labels.mat file and it is a bit difficult because I only have the labels for each session and not a file for the labels and I couldn't fine the file of how you built that. :D

**Comment by Abhishek-Iyer1** [comment]
If downloading the labels creates separate files for labels, you can combine it similarly as we do in the dataset file. Since the data itself is in different sessions. Iterate over all the files, load the labels in an array and append that to an array that you maintain over the whole loop. That should give you all the labels in one file. And then if needed, you can use one hot encoding or any other preprocessing as per your use case. I hope that helps

**Comment by maneaionut** [comment]
Did you use the SEED or SEES-IV database?

**Comment by Abhishek-Iyer1** [comment]
The SEED dataset
